font_family Cartograph CF
bold_font Cartograph CF Bold
italic_font Cartograph CF Italic
bold_italic_font Cartograph CF Bold Italic

font_size 13.0
line_spacing 1.2

symbol_map U+F000-U+F0FF FontAwesome
symbol_map U+E000-U+EFFF,U+F100-U+F8FF,U+F0000-U+FFFFD,U+100000-U+10FFFD Symbols Nerd Font Mono
symbol_map U+2500-U+259F Noto Sans Mono
symbol_map U+2190-U+21FF,U+2300-U+23FF,U+25A0-U+25FF,U+2600-U+26FF,U+2700-U+27BF,U+2800-U+28FF Noto Sans Symbols 2

background_opacity 0.7
background_blur 1
