source = ~/p/eggfriedrice.nvim/extras/hyprland/eggfriedrice.conf

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    outer_color = $yellow          # focus
    inner_color = $bg
    font_color = $fg
    fade_on_empty = true
    placeholder_text =
    halign = center
    valign = center
}
