background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    outer_color = rgb(89b4fa)      # $blue
    inner_color = rgb(1e1e2e)      # $base
    font_color = rgb(cdd6f4)       # $text
    fade_on_empty = true
    placeholder_text =
    halign = center
    valign = center
}
